### ISSUE TITLE
Object does not inherit before and after hooks from parent if constructor is overrided.

### ISSUE THREAD

**Issue by LuminescentMoon** [luapower/oo#1]
``` lua
local oo = require('oo')

local ABC = oo.ABC()

function ABC:before_init(...)
  print(1)
  return ...
end

function ABC:init(...)
  print(2)
  return ...
end

function ABC:after_init(...)
  print(3)
  return ...
end

local DEF = oo.DEF(ABC)

function DEF:override_init(inherited, ...)
  print(2.5)
  return ...
end

local newObj = DEF()

```

Expected output:

> 1
> 2.5
> 3

Output received:

> 2.5

**Comment by capr** [comment]
You need to call the inherited method when you override a method. That's why you receive it as arg#1. It's up to you where/if you call it.

**Comment by LuminescentMoon** [comment]
Wouldn't it make more sense for the overriding constructor to inherit the before and after hooks of the parent though?

**Comment by capr** [comment]
I don't think so. Overriding should allow you to change the behavior entirely no?

**Comment by capr** [comment]
The before and after hooks are just syntax sugar if you will. They help you generate overrides more easily but there's no hidden list of hooks or anything. It's just function composition resulting in a single overriden method.
